WIP - Issue #78 Implementing Number Format Parser
GSS-Cogs/csvw-check pull request #97
Opened 2021-12-07 11:40 UTC by robons

2021-12-07 11:49 UTC, robons commented on src/main/scala/numberformatparser/NumberFormatParser.scala
> +            case e => Failure(e.getMessage, currentPosition)
todo: log debug?

2021-12-13 14:04 UTC, cjfairchild requested changes
Please see comments for actionable issues - they're minor - one for error catching and likely compiler complaints and another for documentation around the ```ArrayCursor``` class.

2021-12-13 14:04 UTC, cjfairchild commented on src/main/scala/Column.scala
> +      case e =>
Having seen the latter code for debug extensions - I'm not sure the caught exception will be logged at all as there's a conditional as ```debug(error: Throwable)``` in the logging code.

2021-12-13 14:50 UTC, robons commented on src/main/scala/Column.scala
> +      case e =>
> Throwing unspecified e is generally frowned upon
Indeed, I'm just not ready to invest the time necessary to remove all the general catches everywhere right now.

> one could use 'case e : Throwable => ...'
Will do

2021-12-13 14:57 UTC, robons commented on src/main/scala/models/ArrayCursor.scala
> +case class ArrayCursor[T: ClassTag](private val values: Seq[T]) {
Good call

2021-12-13 17:34 UTC, merged